spring:
  datasource:
    username: jeju
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study_db?characterEncoding=utf-8&serverTimezone=UTC
  jpa:
    show-sql: true